<?php


namespace SLackMessage\Test;

use Illuminate\Contracts\Container\BindingResolutionException;
use Illuminate\Foundation\Application;
use Orchestra\Testbench\TestCase;
use SlackMessage\Models\SlackFilterChannel;
use SlackMessage\Models\SlackFilterUser;
use SlackMessage\Providers\SlackProvider;

class SlackFilterUserTest extends TestCase
{
    private $channelSlack;

    /**
     * @throws BindingResolutionException
     */
    protected function setUp(): void
    {
        parent::setUp();
        $this->channelSlack = app()->make(SlackFilterUser::class);
    }

    /**
     * @param  Application $app
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            SlackProvider::class
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function testGetChannels()
    {
        // dd($this->app['config']->get('slack-message'));
        self::assertIsObject($this->channelSlack->get());
    }

    public function testFilterChannels()
    {

        self::assertTrue($this->channelSlack->filter(['@Michael'])->count() >0);
    }

}
