<?php

namespace SlackMessage\Providers;


use Composer\Config;
use GuzzleHttp\Client;
use Illuminate\Support\ServiceProvider;
use SlackMessage\Facades\Slack;
use SlackMessage\Models\BaseFilter;
use SlackMessage\Models\BaseMessage;
use SlackMessage\Models\Sender;
use SlackMessage\Models\SlackFilterChannel;
use SlackMessage\Models\SlackFilterUser;

/**
 * Class SlackProvider
 * @package SlackMessage\Providers
 */
class SlackProvider extends ServiceProvider
{
    /**
     * @var string
     */
    private $path;

    /**
     * Create a new service provider instance.
     *
     * @param  \Illuminate\Contracts\Foundation\Application  $app
     * @return void
     */
    public function __construct($app)
    {
        $this->path = __DIR__.'/../../config/config.php';
        parent::__construct($app);
    }

    /**
     *
     */
    public function boot()
    {
        $this->publishes(
            [
                realpath($this->path) => config_path('slack-message.php')
            ],
            'config'
        );

    }

    /**
     *
     */
    public function register()
    {
        $this->mergeConfigFrom(realpath($this->path), 'slack-message');
        app()->when([
            BaseFilter::class,
            SlackFilterChannel::class,
            SlackFilterUser::class,
            BaseMessage::class
        ])->needs(Client::class)
            ->give(function() {
                return new Client([
                    'base_uri' => config('slack-message.slack_api_url'),
                    'headers'   =>  [
                        'Authorization' =>  'Bearer '.config('slack-message.slack_bot_token'),
                        'Accept'        =>  'application/json',
                        'Content-type'  =>  'application/json',
                        'User-Agent'    =>  'PostmanRuntime/7.21.0'
                    ],
                    'verify'    =>  false
                ]);
            });
        $this->app->alias(Slack::class, 'slack');
        parent::register(); // TODO: Change the autogenerated stub
    }

    /**
     * Get the services provided by the provider.
     *
     * @return array
     */
    public function provides()
    {
        return [Slack::class];
    }


}
