<?php

namespace SLackMessage\Test;

use GuzzleHttp\Client;
use Illuminate\Contracts\Container\BindingResolutionException;
use Orchestra\Testbench\TestCase;
use SlackMessage\Models\BaseMessage;
use SlackMessage\Providers\SlackProvider;

class SlackChannelTest extends TestCase
{
    private $channelSlack;

    protected function setUp(): void
    {
        parent::setUp();

        $client = $this->createMock(Client::class);

        $this->channelSlack = new BaseMessage($client);
    }

    /**
     * @param  \Illuminate\Foundation\Application $app
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            SlackProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub
    }

    public function testSend()
    {
        $this->channelSlack->to(['#general'])->send('TESTE');
        self::assertTrue(true);
    }
}
